"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence that do not exceed four million (fCC: the nth term), find the sum of the even-valued terms.
"""

def fibo_evensum(n):
    a = 1
    b = 2
    evensum = 2
    for i in range(3, int(n) + 1):
        fib = a + b 
        if fib % 2 == 0 :
           evensum += fib
        
        a = b
        b = fib

    return evensum

def fib_donotexceed(value):
    a = 1
    b = 2
    c = 0
    count = 1
    while c < int(value):
        count += 1
        c = a + b
        a = b
        b = c
    else:
        return count



if __name__ == '__main__':
    value = input("Set the limit of Fibonacci sequence: ")
    print(fib_donotexceed(value))
    n = input("Sum of even-valued terms do not exceed nth term, n?: ")
    print(fibo_evensum(n))
    
        
